### ISSUE TITLE
claim bcoin ไม่เข้า wallet 

### ISSUE THREAD

**Issue by GetnaWaOe** [verichains/public-audit-reports#10]
7:46 AM 12/22/2021 | 0x917a9696eaf1842fd2e4dada6323f8f7c1462cdd | 41.38 | successful | 0x6bff015e85a304b019e3bb7d71fbc6fb05caca24252782525ed2f1facc33ac9c  ไม่เข้า wallet

**Comment by sexysteph4u** [comment]
???

**Comment by sexysteph4u** [comment]
> 7:46 AM 12/22/2021 | 0x917a9696eaf1842fd2e4dada6323f8f7c1462cdd | 41.38 | successful | 0x6bff015e85a304b019e3bb7d71fbc6fb05caca24252782525ed2f1facc33ac9c ไม่เข้า wallet

What's is that
