### ISSUE TITLE
Bomb crypto Bcoin Claimed but not appearing in wallet

### ISSUE THREAD

**Issue by darckii** [verichains/public-audit-reports#5]
My address is 0x069eE5BC9F9C6A91B1EF5C9B4D77773F3E63cC18 and i claimed 57 coins but it doesn't show in my wallet and it has passed 6 hours

**Comment by Leoolima13** [comment]
Meu tb aconteceu mesmo a mesma coisa, duas contas... tem quase 8 horas .

**Comment by Leoolima13** [comment]
se chegar a resolver o seu, comenta aqui. :D
